### ISSUE TITLE
switch continue with label

### ISSUE THREAD

**Issue by tgulacsi** [bobg/pk#1]
https://github.com/bobg/pk/blob/d43e393588986682a4ead7218a0c1dc3b0532cfc/encode.go#L175

You want to continue the loop, not the switch...

**Comment by bobg** [comment]
I'm not clear on what you're suggesting. The `continue` _does_ continue the loop, not the switch. (What would it mean to continue a switch?)

Perhaps you mean that because the `continue` is inside a `switch`, it's not clear at a glance which loop it belongs to, and a label would make it clearer?

**Comment by tgulacsi** [comment]
I'm sorry, you're right, I've mixed the continue with "break".




On Wed, Nov 20, 2019 at 3:51 PM +0100, "Bob Glickstein" <notifications@github.com> wrote:












I'm not clear on what you're suggesting. The continue does continue the loop, not the switch. (What would it mean to continue a switch?)


Perhaps you mean that because the continue is inside a switch, it's not clear at a glance which loop it belongs to, and a label would make it clearer?
